include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - lib/**.g.dart
    - lib/**.freezed.dart
    - lib/**.gr.dart
    - lib/generated/**
    - lib/**/**.config.dart
  errors:
    avoid_print: error
  language:
    strict-casts: true
    strict-inference: true
linter:
  rules:
    - always_use_package_imports
    - annotate_overrides
    - avoid_empty_else
    - avoid_print
    - avoid_redundant_argument_values
    - avoid_void_async
    - await_only_futures
    - directives_ordering
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_final_fields
    - prefer_single_quotes
    - require_trailing_commas
    - sort_child_properties_last
    - unnecessary_const
    - use_build_context_synchronously
    - use_key_in_widget_constructors
    - use_super_parameters
