import 'package:coore/src/config/entities/navigation_config_entity.dart';
import 'package:coore/src/dev_tools/core_logger.dart';
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

/// Core router that configures and provides the GoRouter instance.
///
/// This class is responsible for:
/// - Building the GoRouter with your app's route configuration
/// - Managing the root navigator key
/// - Handling router refresh (e.g., after auth state changes)
/// - Integrating navigation observers for logging
///
/// **Important**: This class does NOT provide navigation methods.
/// Instead, use:
/// - `go_router_builder` generated extensions for type-safe navigation from widgets
/// - Direct `GoRouter` API for navigation from BLoCs/Services
///
/// Example (from widget):
/// ```dart
/// context.goUserDetails(id: '123'); // Generated by go_router_builder
/// ```
///
/// Example (from BLoC):
/// ```dart
/// final router = getIt<GoRouter>();
/// router.push(UserDetailsRoute(id: '123').location);
/// ```
class CoreRouter {
  CoreRouter({
   
    required NavigationConfigEntity navigationConfigEntity,
    required bool shouldLog,
  }) : 
       _configEntity = navigationConfigEntity,
       _shouldLog = shouldLog,
       refreshListenable = navigationConfigEntity.refreshListenable {
    _goRouter = _createRouter();
  }

 
  final NavigationConfigEntity _configEntity;
  final Listenable? refreshListenable;
  final bool _shouldLog;

  late GoRouter _goRouter;

 
  /// Provides the configured GoRouter instance.
  ///
  /// This is the main API your app will use for navigation.
  /// Register this in your DI container to enable context-less navigation:
  ///
  /// ```dart
  /// getIt.registerLazySingleton<GoRouter>(() => getIt<CoreRouter>().router);
  /// ```
  GoRouter get router => _goRouter;

  /// Re-creates the router with the current configuration.
  ///
  /// Call this when routes need to be updated dynamically.
  /// Typically used after authentication state changes or when
  /// route guards need to be re-evaluated.
  void refreshRouter() {
    _goRouter = _createRouter();
  }

  GoRouter _createRouter() {
    return GoRouter(
      navigatorKey: _configEntity.navigatorKey,
      routes: _configEntity.routes,
      errorBuilder: _configEntity.errorBuilder ?? _defaultErrorWidget,
      debugLogDiagnostics:_shouldLog,
      restorationScopeId: 'coreRouter',
      redirect: _configEntity.redirect,
      refreshListenable: refreshListenable,
      observers: [
        ..._configEntity.navigationObservers,
      ],
    );
  }

  Widget _defaultErrorWidget(BuildContext context, GoRouterState state) {
    return Scaffold(
      appBar: AppBar(title: const Text('Error')),
      body: Center(child: Text(state.error?.message ?? '')),
    );
  }
}

