import 'package:coore/src/config/entities/navigation_config_entity.dart';
import 'package:coore/src/dev_tools/core_logger.dart';
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

/// Core router that configures and provides the GoRouter instance.
///
/// This class is responsible for:
/// - Building the GoRouter with your app's route configuration
/// - Managing the root navigator key
/// - Handling router refresh (e.g., after auth state changes)
/// - Integrating navigation observers for logging
///
/// **Important**: This class does NOT provide navigation methods.
/// Instead, use:
/// - `go_router_builder` generated extensions for type-safe navigation from widgets
/// - Direct `GoRouter` API for navigation from BLoCs/Services
///
/// Example (from widget):
/// ```dart
/// context.goUserDetails(id: '123'); // Generated by go_router_builder
/// ```
///
/// Example (from BLoC):
/// ```dart
/// final router = getIt<GoRouter>();
/// router.push(UserDetailsRoute(id: '123').location);
/// ```
class CoreRouter {
  CoreRouter({
    required CoreLogger logger,
    required NavigationConfigEntity navigationConfigEntity,
    required bool shouldLog,
  }) : _logger = logger,
       _configEntity = navigationConfigEntity,
       _shouldLog = shouldLog,
       refreshListenable = navigationConfigEntity.refreshListenable {
    _goRouter = _createRouter();
  }

  final CoreLogger _logger;
  final NavigationConfigEntity _configEntity;
  final Listenable? refreshListenable;
  final bool _shouldLog;

  late GoRouter _goRouter;

  /// The root navigator key used by GoRouter.
  ///
  /// This key is essential for:
  /// - Accessing the root navigator from anywhere in the app
  /// - Showing dialogs, snackbars, and overlays from BLoCs/Services
  /// - Context-less navigation scenarios
  static final GlobalKey<NavigatorState> _routeNavigationKey =
      GlobalKey<NavigatorState>(debugLabel: 'root');

  /// Provides the root navigator key to the app.
  ///
  /// Use this when you need to access the root BuildContext for:
  /// - Showing dialogs from BLoCs: `showDialog(context: CoreRouter.rootNavigatorKey.currentContext!)`
  /// - Displaying snackbars from services
  /// - Any other context-dependent operations outside the widget tree
  static GlobalKey<NavigatorState> get rootNavigatorKey => _routeNavigationKey;

  /// Provides the configured GoRouter instance.
  ///
  /// This is the main API your app will use for navigation.
  /// Register this in your DI container to enable context-less navigation:
  ///
  /// ```dart
  /// getIt.registerLazySingleton<GoRouter>(() => getIt<CoreRouter>().router);
  /// ```
  GoRouter get router => _goRouter;

  /// Re-creates the router with the current configuration.
  ///
  /// Call this when routes need to be updated dynamically.
  /// Typically used after authentication state changes or when
  /// route guards need to be re-evaluated.
  void refreshRouter() {
    _goRouter = _createRouter();
  }

  GoRouter _createRouter() {
    return GoRouter(
      navigatorKey: _routeNavigationKey,
      routes: _configEntity.routes,
      errorBuilder: _configEntity.errorBuilder ?? _defaultErrorWidget,
      debugLogDiagnostics: _configEntity.shouldUsePackageLog,
      restorationScopeId: 'coreRouter',
      redirect: _configEntity.redirect,
      refreshListenable: refreshListenable,
      observers: [
        if (_shouldLog) CoreNavigationObserver(_logger),
        ..._configEntity.navigationObservers,
      ],
    );
  }

  Widget _defaultErrorWidget(BuildContext context, GoRouterState state) {
    return Scaffold(
      appBar: AppBar(title: const Text('Error')),
      body: Center(child: Text(state.error?.message ?? '')),
    );
  }
}

/// Type alias for backward compatibility.
///
/// Use [CoreRouter] instead.
@Deprecated('Use CoreRouter instead')
typedef CoreNavigator = CoreRouter;

/// Type alias for backward compatibility.
///
/// Use [CoreRouter] instead.
@Deprecated('Use CoreRouter instead')
typedef GoRouterNavigator = CoreRouter;

/// Navigation observer for logging and tracking navigation events.
///
/// This observer logs all navigation actions (push, pop, replace, remove)
class CoreNavigationObserver extends NavigatorObserver {
  CoreNavigationObserver(this._logger);
  final CoreLogger _logger;

  @override
  void didPush(Route<dynamic> route, Route<dynamic>? previousRoute) {
    _logAndTrack('PUSH', route, previousRoute);
    super.didPush(route, previousRoute);
  }

  @override
  void didPop(Route<dynamic> route, Route<dynamic>? previousRoute) {
    _logAndTrack('POP', previousRoute, route);
    super.didPop(route, previousRoute);
  }

  @override
  void didReplace({Route<dynamic>? newRoute, Route<dynamic>? oldRoute}) {
    _logAndTrack('REPLACE', newRoute, oldRoute);
    super.didReplace(newRoute: newRoute, oldRoute: oldRoute);
  }

  @override
  void didRemove(Route<dynamic> route, Route<dynamic>? previousRoute) {
    _logAndTrack('REMOVE', route, previousRoute);
    super.didRemove(route, previousRoute);
  }

  void _logAndTrack(
    String action,
    Route<dynamic>? route,
    Route<dynamic>? previousRoute,
  ) {
    final currentRouteInfo = _extractRouteInfo(route);
    final previousRouteInfo = _extractRouteInfo(previousRoute);

    _logger.debug(
      'Navigation [$action] → Current: $currentRouteInfo | Previous: $previousRouteInfo',
    );
  }

  String _extractRouteInfo(Route<dynamic>? route) {
    if (route == null) return 'None';

    // GoRouter populates route.settings.name with the route's name or path.
    final routeName = route.settings.name;
    if (routeName != null && routeName.isNotEmpty) {
      return routeName;
    }

    // Fallback to the runtime type if no name is available
    return route.runtimeType.toString();
  }
}
