// c:\Projects\coore\lib\src\navigation.dart exports
// generated by: https://marketplace.visualstudio.com/items?itemName=elmsec.dart-flutter-exports:

export 'screen_params/screen_params.dart';
export 'core_navigator.dart';