name: strata_state
description: BLoC state utilities and ApiStateHandler lifecycle management for Strata framework.
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.0.0
  flutter: ">=3.0.0"

dependencies:
  device_info_plus: ^12.2.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  fpdart: ^1.1.0
  get_it: ^9.0.5
  hydrated_bloc: ^10.0.0
  package_info_plus: ^9.0.0
  skeletonizer: ^2.1.0+1
  strata_core:
    path: ../strata_core

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
