// c:\Projects\coore\lib\src\config.dart exports
// generated by: https://marketplace.visualstudio.com/items?itemName=elmsec.dart-flutter-exports:

export 'entities/entities.dart';
export 'service/service.dart';
export 'core_config.dart';